# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13bcefa89a66290d9d0e0910f650d4204cb922af11d8205394eb7c4151ba97b81d536d19b1a807deff7ba9329cad128f4e17023aeace5b174771fb4baf112a17

test:
  secret_key_base: 97d018547a3db743c6427fa116aff341205821e612a4230068d18b98a963bf0de49c4c21c9d2be2a8a04a216e2154fd236c1af8be85d6c4e1b1ee10931fdaa77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
